Resources:
  Phpcloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 30
      Description: phpapplication
      InstanceType: t2.micro
      Name: phpexampleapp
      OwnerArn: 
    Repositories: 
#    - Repository
#      - endavago
# Path to be cloned in the cloud9 environment /home/USER_NAME/environment/REPOSITORY_NAME
        #PathComponent: /s3
# Origin URL that would be cloned into the ambient https://path/directory/REPOSITORY_NAME
        RepositoryUrl: git@github.com:zelfick/Cloudformation.git
#  SubnetId: String
      Tags: 
#    - Tag
        - 
          Key: "Owner"
          Value: "Jorge Herran"
        - 
          Key: "Organization"
          Value: "Valorit"